---
- name: install erlang-solutions gpg key
  become: yes
  apt_key:
    url: https://packages.erlang-solutions.com/debian/erlang_solutions.asc
    state: present

- name: install erlang-solutions repository
  become: yes
  apt_repository:
    repo: deb https://packages.erlang-solutions.com/debian stretch contrib
    state: present

- name: install erlang and elixir
  become: yes
  apt: name={{item}} state=present
  with_items:
    - esl-erlang=1:20.2.2
    - elixir=1.6.1-1
